ALTER TABLE `user` DROP PRIMARY KEY;

ALTER TABLE `user` ADD COLUMN `new_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE `user` DROP COLUMN `id`;

ALTER TABLE `user` MODIFY `id` BIGINT(20) UNSIGNED NOT NULL;

ALTER TABLE `user` CHANGE COLUMN `new_id` `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT;

